"""Tests for FakeTTS — the CI/test TTS engine."""

from __future__ import annotations

import pytest

from ebook2audiobook.models.cast import VoiceRef
from ebook2audiobook.tts.fake_tts import FakeTTS

_FAKE_VOICE = VoiceRef(engine="fake", voice_id="fake-narrator")


class TestFakeTTS:
    def test_engine_name(self):
        tts = FakeTTS()
        assert tts.engine_name == "fake"

    def test_list_voices(self):
        tts = FakeTTS()
        voices = tts.list_voices()
        assert len(voices) >= 1
        assert all("id" in v and "name" in v for v in voices)

    def test_synthesize_returns_bytes(self):
        tts = FakeTTS()
        wav = tts.synthesize("Hello world.", _FAKE_VOICE)
        assert isinstance(wav, bytes)
        assert len(wav) > 44  # at least the WAV header

    def test_wav_header_riff(self):
        """Generated bytes must be a valid RIFF/WAV file."""
        tts = FakeTTS()
        wav = tts.synthesize("Test sentence.", _FAKE_VOICE)
        # RIFF magic bytes at offset 0
        assert wav[:4] == b"RIFF"
        # WAVE magic bytes at offset 8
        assert wav[8:12] == b"WAVE"
        # fmt chunk at offset 12
        assert wav[12:16] == b"fmt "

    def test_silence_mode(self):
        tts = FakeTTS(mode="silence")
        wav = tts.synthesize("Hello.", _FAKE_VOICE)
        # All PCM data after the header should be zero (silence).
        header_size = 44
        pcm = wav[header_size:]
        assert all(b == 0 for b in pcm)

    def test_tone_mode(self):
        tts = FakeTTS(mode="tone")
        wav = tts.synthesize("Hello.", _FAKE_VOICE)
        assert wav[:4] == b"RIFF"
        # PCM data should NOT be all zeros for a tone.
        header_size = 44
        pcm = wav[header_size:]
        assert any(b != 0 for b in pcm)

    def test_duration_proportional_to_words(self):
        tts = FakeTTS(sample_rate=22050)
        short_wav = tts.synthesize("Hi.", _FAKE_VOICE)
        long_wav = tts.synthesize("This is a much longer sentence with many words.", _FAKE_VOICE)
        assert len(long_wav) > len(short_wav)

    def test_minimum_duration(self):
        """Even a single character must produce at least 200 ms of audio."""
        tts = FakeTTS(sample_rate=22050)
        wav = tts.synthesize("A", _FAKE_VOICE)
        # 200 ms = 0.2 s × 22050 samples × 2 bytes + 44 header
        min_bytes = 44 + int(0.2 * 22050) * 2
        assert len(wav) >= min_bytes

    def test_invalid_mode_raises(self):
        with pytest.raises(ValueError, match="mode must be"):
            FakeTTS(mode="invalid")

    def test_exceeds_max_chars_raises(self):
        tts = FakeTTS()
        # max_chars for FakeTTS is 100_000 — craft text just over it.
        huge_text = "a" * (tts.max_chars + 1)
        with pytest.raises(ValueError, match="exceeds FakeTTS.max_chars"):
            tts.synthesize(huge_text, _FAKE_VOICE)
